//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechAppProject.DBModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ChatId { get; set; }
        public int CustomerId { get; set; }
        public int WorkshopId { get; set; }
        public string Message { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
