//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechAppProject.DBModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        public int WorkshopId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string WorkshopName { get; set; }
        public string OwerName { get; set; }
        public string PhoneNbr { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string StreetNbr { get; set; }
        public string ZipCode { get; set; }
    }
}
